// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicCTA: typeof import('./components/widgets/BasicCTA.vue')['default']
    BasicFAQs: typeof import('./components/widgets/BasicFAQs.vue')['default']
    BasicFeatures: typeof import('./components/widgets/BasicFeatures.vue')['default']
    Footer: typeof import('./components/widgets/Footer.vue')['default']
    Header: typeof import('./components/widgets/Header.vue')['default']
    Hero: typeof import('./components/widgets/Hero.vue')['default']
    HighlightedPosts: typeof import('./components/widgets/HighlightedPosts.vue')['default']
    Logo: typeof import('./components/widgets/Logo.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NRow: typeof import('naive-ui')['NRow']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PageContent: typeof import('./components/page-content.vue')['default']
    Pagination: typeof import('./components/widgets/Pagination.vue')['default']
    Picture: typeof import('./components/core/Picture.vue')['default']
    ProjectInfo: typeof import('./components/projectInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stats: typeof import('./components/widgets/Stats.vue')['default']
    StepsFeatures: typeof import('./components/widgets/StepsFeatures.vue')['default']
    StepsLeft: typeof import('./components/widgets/StepsLeft.vue')['default']
    TwoColsFeatures: typeof import('./components/widgets/TwoColsFeatures.vue')['default']
  }
}
