// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicCTA: typeof import('./components/widgets/BasicCTA.vue')['default']
    BasicFAQs: typeof import('./components/widgets/BasicFAQs.vue')['default']
    BasicFeatures: typeof import('./components/widgets/BasicFeatures.vue')['default']
    Footer: typeof import('./components/widgets/Footer.vue')['default']
    Header: typeof import('./components/widgets/Header.vue')['default']
    Hero: typeof import('./components/widgets/Hero.vue')['default']
    HighlightedPosts: typeof import('./components/widgets/HighlightedPosts.vue')['default']
    Logo: typeof import('./components/widgets/Logo.vue')['default']
    PageContent: typeof import('./components/page-content.vue')['default']
    Pagination: typeof import('./components/widgets/Pagination.vue')['default']
    Picture: typeof import('./components/core/Picture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stats: typeof import('./components/widgets/Stats.vue')['default']
    StepsFeatures: typeof import('./components/widgets/StepsFeatures.vue')['default']
    StepsLeft: typeof import('./components/widgets/StepsLeft.vue')['default']
    TwoColsFeatures: typeof import('./components/widgets/TwoColsFeatures.vue')['default']
  }
}
